/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/Feg.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Feg(props) {
  const ref = useRef();
  const { nodes, materials } = useGLTF("./models/Feg.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[0.426, 0.136, -0.184]}>
        <mesh
          geometry={nodes.Mesh_2198.geometry}
          material={materials["Dachziegel, hell"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_1.geometry}
          material={materials["Holz weiss"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_2.geometry}
          material={materials["Metall Stahl mat"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_3.geometry}
          material={materials["Verputz, grobkr"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_4.geometry}
          material={materials["Holz Eiche"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_5.geometry}
          material={materials["Farbe, weiss"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_6.geometry}
          material={materials["Verputz, glatt, "]}
        />
        <mesh
          geometry={nodes.Mesh_2198_7.geometry}
          material={materials.Rahmen}
        />
        <mesh
          geometry={nodes.Mesh_2198_8.geometry}
          material={materials["Holz Palisander"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_9.geometry}
          material={materials["Glas Normalglas"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_10.geometry}
          material={materials["Holz Wenge"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_11.geometry}
          material={materials["Farbe, hellgrau"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_12.geometry}
          material={materials["Beton Brettersch"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_13.geometry}
          material={materials["Holz Nussbaum"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_14.geometry}
          material={materials["Farbe, rot"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_15.geometry}
          material={materials["Beton gestrichen"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_16.geometry}
          material={materials["Holz Fichte"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_17.geometry}
          material={materials["Metall Kupfer"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_18.geometry}
          material={materials["Holz Buche"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_19.geometry}
          material={materials["Verputz, Decke, "]}
        />
        <mesh
          geometry={nodes.Mesh_2198_20.geometry}
          material={materials["Metall Aluminium"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_21.geometry}
          material={materials.Rasengitterstein}
        />
        <mesh
          geometry={nodes.Mesh_2198_22.geometry}
          material={materials["Farbe, schwarz"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_23.geometry}
          material={materials["Farbe, hochweiss"]}
        />
        <mesh
          geometry={nodes.Mesh_2198_24.geometry}
          material={materials["01_Holz"]}
        />
      </group>
      <group position={[-0.146, -0.058, 0.172]}>
        <mesh
          geometry={nodes.Mesh_2699.geometry}
          material={materials["Pflaster, Block,"]}
        />
        <mesh
          geometry={nodes.Mesh_2699_1.geometry}
          material={materials["Farbe, dunkelgra"]}
        />
        <mesh
          geometry={nodes.Mesh_2699_2.geometry}
          material={materials.Rasengitterstein}
        />
        <mesh
          geometry={nodes.Mesh_2699_3.geometry}
          material={materials["Beton gestrichen"]}
        />
        <mesh
          geometry={nodes.Mesh_2699_4.geometry}
          material={materials["Natur, Gras, hel"]}
        />
      </group>
      <group position={[-2.031, 0.268, -0.139]}>
        <mesh
          geometry={nodes.Mesh_3238.geometry}
          material={materials["Verputz, glatt, "]}
        />
        <mesh
          geometry={nodes.Mesh_3238_1.geometry}
          material={materials["Beton gestrichen"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_2.geometry}
          material={materials["Holz Zebrano"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_3.geometry}
          material={materials["Metall Stahl mat"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_4.geometry}
          material={materials["Farbe, weiss"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_5.geometry}
          material={materials["01_Holz"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_6.geometry}
          material={materials.Rahmen}
        />
        <mesh
          geometry={nodes.Mesh_3238_7.geometry}
          material={materials["Glas Normalglas"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_8.geometry}
          material={materials["Beton, Sichtbeto"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_9.geometry}
          material={materials["Farbe, bordeaux"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_10.geometry}
          material={materials["Beton Sichtbeton"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_11.geometry}
          material={materials["Kies, beige"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_12.geometry}
          material={materials["Holz Ahorn"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_13.geometry}
          material={materials["Metall Chrom"]}
        />
        <mesh
          geometry={nodes.Mesh_3238_14.geometry}
          material={materials["Metall Streckmet"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/Feg.glb");
