/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/Feg.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Feg(props) {
  const ref = useRef();
  const { nodes, materials } = useGLTF("./models/TestFegShader.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-2.031, 0.268, -0.139]}>
        <mesh geometry={nodes.Mesh_3238.geometry} material={materials.Material} />
        <mesh geometry={nodes.Mesh_3238_1.geometry} material={materials.Outline} />
      </group>
    </group>
  )
}

useGLTF.preload("./models/TestFegShader.glb");
