/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/Feg.glb 
*/

import React, {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
} from "react";
import PropTypes from "prop-types";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import gsap from "gsap";

export function Feg({
  isFullScreen,
  cameraPosition,
  useCameraPosition,
  setUseCameraPosition,
  ...props
}) {
  const tl = useRef();
  const { camera } = useThree();
  const [mouseX, setMouseX] = useState(0);
  const [mouseY, setMouseY] = useState(0);
  useLayoutEffect(() => {
    setUseCameraPosition(false);
  }, []);
  useEffect(() => {
    const handleMouseMove = (e) => {
      const windowHalfX = window.innerWidth / 2;
      const windowHalfY = window.innerHeight / 2;
      setMouseX((e.clientX - windowHalfX) / 1000);
      setMouseY((e.clientY - windowHalfY) / 2000);
    };

    document.addEventListener("mousemove", handleMouseMove);
    return () => document.removeEventListener("mousemove", handleMouseMove);
  }, []);

  // Animate camera based on mouse position
  const animateCamera = useCallback(() => {
    if (!isFullScreen) {
      camera.position.x += (mouseX - camera.position.x) * 0.05;
      camera.position.y += (-mouseY - camera.position.y) * 0.05;
      camera.lookAt(0, 0, 0);
    }
  }, [isFullScreen, mouseX, mouseY, camera]);

  useFrame(() => {
    animateCamera();
    if (useCameraPosition) {
      tl.current = gsap.timeline();
      tl.current.to(camera.position, {
        x: cameraPosition[0],
        y: cameraPosition[1],
        z: cameraPosition[2],
        duration: 2,
        ease: "power3.inOut",
        onUpdate: () => {
          camera.lookAt(0, 0, 0);
        },
      });
      setUseCameraPosition(false);
    }
  });
  const { nodes, materials } = useGLTF("./models/TestFegShader.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-2.031, 0.268, -0.139]}>
        <mesh
          geometry={nodes.Mesh_3238.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Mesh_3238_1.geometry}
          material={materials.Outline}
        />
      </group>
    </group>
  );
}
useGLTF.preload("./models/TestFegShader.glb");

Feg.propTypes = {
  isFullScreen: PropTypes.bool,
  cameraPosition: PropTypes.arrayOf(PropTypes.number).isRequired,
  useCameraPosition: PropTypes.bool.isRequired,
};
useGLTF.preload("./models/TestFegShader.glb");
