/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 src/assets/3d/tokio.glb 
*/

import React, { useEffect, useLayoutEffect, useRef } from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import { gsap } from "gsap";
import { useFrame, useThree } from "@react-three/fiber";

export const FLOOR_HEIGHT = 2.3;
export const NG_FLOOR = 3.2;
export function Tokio(props) {
  const ref = useRef();
  const tl = useRef();
  const { nodes, materials, animations } = useGLTF("./models/tokio.glb");
  const { actions } = useAnimations(animations, ref);
  const { camera } = useThree();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useEffect(() => {
    actions["Take 001"].play();
  }, []);

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    tl.current
      .from(
        ref.current.position,
        {
          duration: 3,
          y: -FLOOR_HEIGHT * (NG_FLOOR - 1),
          ease: "power3.inOut",
        },
        0
      )
      .to(
        camera.position,
        {
          duration: 2,
          y: 0,
          x: 0,
          z: 10,
          ease: "power3.inOut",
        },
        1
      )
      .to(
        camera.position,
        {
          duration: 2,
          y: 5,
          x: 10,
          z: 0,
          ease: "power3.inOut",
          on: () => {
            camera.lookAt(0, 0, 0);
          },
        },
        3
      );
  }, []);

  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <group name="scenegltf">
          <group name="littlest_tokyo_sunset_-_3d_editor_challengeglb">
            <group
              name="Sketchfab_model"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.013}
            >
              <group name="root">
                <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                  <group
                    name="RootNode_(gltf_orientation_matrix)_0"
                    rotation={[-Math.PI / 2, 0, 0]}
                  >
                    <group name="RootNode_(model_correction_matrix)_1">
                      <group
                        name="4cd116fc63ca40809810ca0842dc78edfbx_2"
                        rotation={[Math.PI / 2, 0, 0]}
                      >
                        <group name="_3">
                          <group name="RootNode_4">
                            <group name="_5">
                              <group name="GLTF_created_0">
                                <group
                                  name="Object078_53"
                                  position={[76.075, 163.937, 118.597]}
                                  rotation={[-Math.PI / 3, 0, 0]}
                                  scale={3.099}
                                >
                                  <group
                                    name="_54"
                                    position={[-97.409, -7.128, -96.27]}
                                  >
                                    <group name="Object078_Plastic_Soft_0_55">
                                      <mesh
                                        name="Object_30"
                                        geometry={nodes.Object_30.geometry}
                                        material={materials.Plastic_Soft}
                                      />
                                    </group>
                                  </group>
                                </group>
                                <group
                                  name="Object608_75"
                                  position={[-54.38, 114.483, -87.573]}
                                  rotation={[-Math.PI / 2, 0, 0]}
                                  scale={3.099}
                                >
                                  <group
                                    name="_76"
                                    position={[-55.32, -73.646, -80.314]}
                                  >
                                    <group name="Object608_metalmat_0_77">
                                      <mesh
                                        name="Object_58"
                                        geometry={nodes.Object_58.geometry}
                                        material={materials.metalmat}
                                      />
                                    </group>
                                    <group name="Object608_paintmat_0_78">
                                      <mesh
                                        name="Object_60"
                                        geometry={nodes.Object_60.geometry}
                                        material={materials.paintmat}
                                      />
                                    </group>
                                  </group>
                                </group>
                                <group
                                  name="wire7_91"
                                  position={[53.443, -91.07, 179.833]}
                                  rotation={[-1.534, 0, 0]}
                                >
                                  <group
                                    name="_92"
                                    position={[-138.488, 205.266, 96.473]}
                                  >
                                    <group name="wire7_normal_0_93">
                                      <mesh
                                        name="Object_87"
                                        geometry={nodes.Object_87.geometry}
                                        material={materials.normal}
                                      />
                                    </group>
                                  </group>
                                </group>
                                <group
                                  name="Object675_97"
                                  position={[85.462, -196.519, -246.386]}
                                  rotation={[-Math.PI / 2, 0, 3.113]}
                                >
                                  <group
                                    name="Object680_103"
                                    position={[-12.887, 0, 8.351]}
                                  >
                                    <group
                                      name="_104"
                                      position={[12.887, 0, 68.079]}
                                    >
                                      <group name="Object680_metalmat_0_105">
                                        <mesh
                                          name="Object_106"
                                          geometry={nodes.Object_106.geometry}
                                          material={materials.metalmat}
                                        />
                                      </group>
                                    </group>
                                  </group>
                                  <group
                                    name="Object681_106"
                                    position={[14.29, 0, 8.351]}
                                  >
                                    <group
                                      name="_107"
                                      position={[12.887, 0, 68.079]}
                                    >
                                      <group name="Object681_metalmat_0_108">
                                        <mesh
                                          name="Object_110"
                                          geometry={nodes.Object_110.geometry}
                                          material={materials.metalmat}
                                        />
                                      </group>
                                    </group>
                                  </group>
                                  <group name="_98" position={[0, 0, 76.43]}>
                                    <group name="Object675_metalmat_0_99">
                                      <mesh
                                        name="Object_96"
                                        geometry={nodes.Object_96.geometry}
                                        material={materials.metalmat}
                                      />
                                    </group>
                                    <group name="Object675_paintmat_0_100">
                                      <mesh
                                        name="Object_98"
                                        geometry={nodes.Object_98.geometry}
                                        material={materials.paintmat}
                                      />
                                    </group>
                                    <group name="Object675_glassmat_0_101">
                                      <mesh
                                        name="Object_100"
                                        geometry={nodes.Object_100.geometry}
                                        material={materials.glassmat}
                                      />
                                    </group>
                                    <group name="Object675_outline_0_102">
                                      <mesh
                                        name="Object_102"
                                        geometry={nodes.Object_102.geometry}
                                        material={materials.outline}
                                      />
                                    </group>
                                  </group>
                                </group>
                                <group
                                  name="Object532_109"
                                  position={[-29.258, -38.731, -7.815]}
                                  rotation={[-Math.PI / 2, 0, -0.698]}
                                  scale={3.099}
                                >
                                  <group
                                    name="_110"
                                    position={[-17.707, -77.448, -30.882]}
                                    rotation={[0, 0, 0.698]}
                                  >
                                    <group name="Object532_normal_0_111">
                                      <mesh
                                        name="Object_114"
                                        geometry={nodes.Object_114.geometry}
                                        material={materials.normal}
                                      />
                                    </group>
                                  </group>
                                </group>
                                <group
                                  name="Object689_115"
                                  position={[-245.525, -161.782, -259.308]}
                                  rotation={[-1.627, -0.067, -0.7]}
                                >
                                  <group name="_116" rotation={[0, 0, 0.698]}>
                                    <group name="Object689_metalmat_0_117">
                                      <mesh
                                        name="Object_122"
                                        geometry={nodes.Object_122.geometry}
                                        material={materials.metalmat}
                                      />
                                    </group>
                                  </group>
                                </group>
                                <group
                                  name="Object649_79"
                                  position={[-85.046, 5.403, -25.433]}
                                  rotation={[-Math.PI / 2, 0, 0]}
                                >
                                  <group name="Object649_normal_0_80">
                                    <mesh
                                      name="Object_63"
                                      geometry={nodes.Object_63.geometry}
                                      material={materials.normal}
                                    />
                                  </group>
                                  <group name="Object649_paintmat_0_81">
                                    <mesh
                                      name="Object_65"
                                      geometry={nodes.Object_65.geometry}
                                      material={materials.paintmat}
                                    />
                                  </group>
                                  <group name="Object649_metalmat_0_82">
                                    <mesh
                                      name="Object_67"
                                      geometry={nodes.Object_67.geometry}
                                      material={materials.metalmat}
                                    />
                                  </group>
                                  <group name="Object649_Plastic_Soft_0_83">
                                    <mesh
                                      name="Object_69"
                                      geometry={nodes.Object_69.geometry}
                                      material={materials.Plastic_Soft}
                                    />
                                  </group>
                                </group>
                                <group
                                  name="Object705_188"
                                  position={[-85.046, 5.403, -25.433]}
                                  rotation={[-Math.PI / 2, 0, 0]}
                                >
                                  <group name="Object705_Material_#5516_0_189">
                                    <mesh
                                      name="Object_211"
                                      geometry={nodes.Object_211.geometry}
                                      material={materials.Material_5516}
                                    />
                                  </group>
                                </group>
                                <group
                                  name="Object622_200"
                                  position={[-85.046, 5.403, -25.433]}
                                  rotation={[-Math.PI / 2, 0, 0]}
                                >
                                  <group name="Object622_alpha_0_201">
                                    <mesh
                                      name="Object_227"
                                      geometry={nodes.Object_227.geometry}
                                      material={materials.alpha_0}
                                    />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group name="AmbientLight_1" position={[0, 3.339, 0]} />
        </group>
        <group name="AmbientLight" position={[0, 3.172, 0]} />
      </group>
    </group>
  );
}

useGLTF.preload("./models/tokio.glb");
