/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/TestFegShader.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TestFegShader.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.031, 0.268, -0.139]}>
        <mesh geometry={nodes.Mesh_3238.geometry} material={materials.Material} />
        <mesh geometry={nodes.Mesh_3238_1.geometry} material={materials.Outline} />
      </group>
    </group>
  )
}

useGLTF.preload('/TestFegShader.glb')
